### ISSUE TITLE
Error opening unit    9: File "parm/complex_*.inpcrd" is missing or unreadable

### ISSUE THREAD

**Issue by EveniltonPCosta** [sahakyanhk/iPBSA#2]
[iPBSA_byEvenilton.zip](https://github.com/sahakyanhk/iPBSA/files/10169873/iPBSA_byEvenilton.zip)
Myself and other colleagues tried to use the iPBSA.sh but without success.
We managed to edit the script at some points but at others, unfortunately, without success.
Could you help us solve these problems?
If necessary, I can send you the receiver and ligand PDBs files.

Kind regards,
Evenilton

(gmxMMPBSA) evenilton@AMD-RTX2080:~/Documentos/iPBSA$ bash iPBSA.sh -r 7BV4_new.pdb -l /home/evenilton/Documentos/iPBSA/ligantes -n 24 -c bcc
bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by bash)

==================================================
Summary of pdb4amber for: 7BV4_new.pdb
===================================================

----------Chains
The following (original) chains have been found:
A

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
None
-----------Non-standard-resnames

---------- Mising heavy atom(s)

None

antechamber

/home/evenilton/Documentos/iPBSA/parm
mol *
mkdir: could not create directory “rec_nonprot.pdb”: File exists
mkdir: could not create directory “rec.pdb”: File exists
mkdir: could not create directory “rec_renum.txt”: File exists
mkdir: could not create directory “rec_sslink”: File exists
mkdir: could not create directory “rec_water.pdb”: File exists

antechamber (frcmod)

iPBSA.sh: line 144: cd: too many arguments
/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)
Cannot open file (*.mol2) with mode (r).
No such file or directory

tleap prot

-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/prep to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd to search path.
-f: Source inp/prot_tleap.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./inp/prot_tleap.in
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/parm10.dat
Reading title:
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/frcmod.ff14SB
Reading force field modification type file (frcmod)
Reading title:
ff14SB protein backbone and sidechain parameters
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/amino12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminoct12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminont12.lib
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Using ArgH and AspGluO modified Bondi2 radii
Loading PDB file: ./parm/rec.pdb
  total atoms in file: 7506
  Leap added 7253 missing atoms according to residue templates:
       7253 H / lone pairs
Checking Unit.

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Warning!
The unperturbed charge of the unit (-12.000000) is not zero.

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Note.
Ignoring the warning from Unit Checking.

Building topology.
Building atom parameters.
Building bond parameters.
Building angle parameters.
Building proper torsion parameters.
Building improper torsion parameters.
 total 3188 improper torsions applied
Building H-Bond parameters.
Incorporating Non-Bonded adjustments.
Not Marking per-residue atom chain types.
Marking per-residue atom chain types.
  (Residues lacking connect0/connect1 - 
   these don't have chain types marked:

	res	total affected

	CGLN	1
	NSER	1
  )
 (no restraints)
	Quit

Exiting LEaP: Errors = 0; Warnings = 1; Notes = 1.

tleap inputs preparation

sed
/home/evenilton/Documentos/iPBSA
foi?
 gbsa.in   min.in   pbsa.in   prot_tleap.in  'tleap_*.in'   xtleap.in

tleap complex

-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/prep to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd to search path.
-f: Source inp/tleap_*.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./inp/tleap_*.in
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/parm10.dat
Reading title:
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/frcmod.ff14SB
Reading force field modification type file (frcmod)
Reading title:
ff14SB protein backbone and sidechain parameters
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/amino12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminoct12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminont12.lib
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Using ArgH and AspGluO modified Bondi2 radii
Loading PDB file: ./parm/rec.pdb
  total atoms in file: 7506
  Leap added 7253 missing atoms according to residue templates:
       7253 H / lone pairs

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Fatal Error!
loadMol2: Improper number of arguments!
usage:  <variable> = loadMol2 <filename>

Exiting LEaP: Errors = 1; Warnings = 0; Notes = 0.

minim

  Error opening unit    9: File "parm/complex_*.inpcrd" is missing or unreadable                
(gmxMMPBSA) evenilton@AMD-RTX2080:~/Documentos/iPBSA$

**Comment by EveniltonPCosta** [comment]
And this error message with this another edited script.

(gmxMMPBSA) evenilton@AMD-RTX2080:~/Documentos/iPBSA$ bash iPBSA_final2.sh -r 7BV4_new.pdb -l ligantes -n 24 -c bcc
bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by bash)
ter 06 dez 2022 17:20:53 -03
/home/evenilton/Documentos/iPBSA/parm/teste2
/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)

Welcome to antechamber 21.0: molecular input file processor.

acdoctor mode is on: check and diagnose problems in the input file.
The atom type is set to gaff; the options available to the -at flag are
    gaff, gaff2, amber, bcc, and sybyl.
-- Check Format for pdb File --
   Status: pass
-- Check Unusual Elements --
   Status: pass
-- Check Open Valences --
   Status: pass
-- Check Geometry --
      for those bonded   
      for those not bonded   
   Status: pass
-- Check Weird Bonds --
   Status: pass
-- Check Number of Units --
   Status: pass
acdoctor mode has completed checking the input file.

/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)
Info: Total number of electrons: 226; net charge: 0

Running: /home/evenilton/miniconda3/envs/gmxMMPBSA/bin/sqm -O -i sqm.in -o sqm.out
/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)

/bin/bash: /home/evenilton/miniconda3/envs/gmxMMPBSA/lib/libtinfo.so.6: no version information available (required by /bin/bash)
ter 06 dez 2022 17:21:54 -03
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/prep to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd to search path.
-f: Source inp/prot_tleap.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./inp/prot_tleap.in
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/parm10.dat
Reading title:
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/frcmod.ff14SB
Reading force field modification type file (frcmod)
Reading title:
ff14SB protein backbone and sidechain parameters
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/amino12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminoct12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminont12.lib
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Using ArgH and AspGluO modified Bondi2 radii
Loading PDB file: ./parm/rec.pdb
  total atoms in file: 9127
  Leap added 5632 missing atoms according to residue templates:
       5632 H / lone pairs
Checking Unit.

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Warning!
The unperturbed charge of the unit (-12.000000) is not zero.

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Note.
Ignoring the warning from Unit Checking.

Building topology.
Building atom parameters.
Building bond parameters.
Building angle parameters.
Building proper torsion parameters.
Building improper torsion parameters.
 total 3188 improper torsions applied
Building H-Bond parameters.
Incorporating Non-Bonded adjustments.
Not Marking per-residue atom chain types.
Marking per-residue atom chain types.
  (Residues lacking connect0/connect1 - 
   these don't have chain types marked:

	res	total affected

	CGLN	1
	NSER	1
  )
 (no restraints)
	Quit

Exiting LEaP: Errors = 0; Warnings = 1; Notes = 1.
tleap INPUT
MINIMIZATION
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/prep to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm to search path.
-I: Adding /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd to search path.
-f: Source inp/tleap_teste2.in.

Welcome to LEaP!
(no leaprc in search path)
Sourcing: ./inp/tleap_teste2.in
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.protein.ff14SB done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/parm10.dat
Reading title:
PARM99 + frcmod.ff99SB + frcmod.parmbsc0 + OL3 for RNA
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/frcmod.ff14SB
Reading force field modification type file (frcmod)
Reading title:
ff14SB protein backbone and sidechain parameters
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/amino12.lib
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminoct12.lib

  Error opening unit    9: File "parm/complex_teste2.inpcrd" is missing or unreadable                
Loading library: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/lib/aminont12.lib
----- Source: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff
----- Source of /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/cmd/leaprc.gaff done
Log file: ./leap.log
Loading parameters: /home/evenilton/miniconda3/envs/gmxMMPBSA/dat/leap/parm/gaff.dat
Reading title:
AMBER General Force Field for organic molecules (Version 1.81, May 2017)
Using ArgH and AspGluO modified Bondi2 radii
Loading PDB file: ./parm/rec.pdb
  total atoms in file: 9127
  Leap added 5632 missing atoms according to residue templates:
       5632 H / lone pairs
Loading Mol2 file: ./parm/teste2/teste2.mol2
Reading MOLECULE named UNL
Loading parameters: ./parm/teste2/teste2.frcmod
Reading force field modification type file (frcmod)
Reading title:
Remark line goes here
Checking Unit.

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Warning!
The unperturbed charge of the unit (-12.003997) is not zero.

/home/evenilton/miniconda3/envs/gmxMMPBSA/bin/teLeap: Note.
Ignoring the warning from Unit Checking.

Building topology.
Building atom parameters.
Building bond parameters.
Building angle parameters.
Building proper torsion parameters.
!FATAL ERROR----------------------------------------
!FATAL:    In file [/home/conda/feedstock_root/build_artifacts/ambertools_1645002103866/work/AmberTools/src/leap/src/leap/unitio.c], line 1803
!FATAL:    Message: 1-4: cannot add bond 14764 14787
This may be caused by duplicate bond specifications;
for example, explicit bond commands in addition to PDB conect records.
!
!ABORTING.
[iPBSA_final2.zip](https://github.com/sahakyanhk/iPBSA/files/10170282/iPBSA_final2.zip)

(gmxMMPBSA) evenilton@AMD-RTX2080:~/Documentos/iPBSA$

**Comment by sahakyanhk** [comment]
Hi Evenilton,

I made some changes in the script and added two examples. I tested it on Debian 8 with ambertools18 and wsl2 with ambertools22.
If it does not work, please attach your files to reproduce the errors.

Thanks,
Harut

**Comment by EveniltonPCosta** [comment]
Thanks Harut!
I'll try again right now.

**Comment by EveniltonPCosta** [comment]
Hi Harut,
Very good! Now it works, but I needed to make some edits to the ligand file:
- The first 14 lines of ligand file, ok, no problems;
- But in the lines "connect" and "master", is necessary to remove them;

REMARK VINA RESULT:      -8.4      3.004      7.396
REMARK  Name = quercertina.pdb
REMARK  6 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: C_2  and  O_22
REMARK    2  A    between atoms: C_6  and  O_21
REMARK    3  A    between atoms: C_8  and  O_20
REMARK    4  A    between atoms: C_9  and  C_10
REMARK    5  A    between atoms: C_13  and  O_19
REMARK    6  A    between atoms: C_14  and  O_18
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
COMPND    quercertina.pdb 
AUTHOR    GENERATED BY OPEN BABEL 3.0.0
ATOM      1  C   UNL A   1      30.577  16.829  20.727  1.00  0.00           C  
ATOM      2  C   UNL A   1      30.428  15.774  21.632  1.00  0.00           C  
ATOM      3  C   UNL A   1      29.511  14.743  21.380  1.00  0.00           C  
ATOM      4  C   UNL A   1      28.746  14.796  20.211  1.00  0.00           C  
ATOM      5  C   UNL A   1      28.897  15.845  19.298  1.00  0.00           C  
ATOM      6  C   UNL A   1      29.812  16.854  19.567  1.00  0.00           C  
ATOM      7  C   UNL A   1      29.308  13.594  22.293  1.00  0.00           C  
ATOM      8  C   UNL A   1      28.236  12.618  21.917  1.00  0.00           C  
ATOM      9  C   UNL A   1      27.571  12.816  20.764  1.00  0.00           C  
ATOM     10  O   UNL A   1      27.807  13.851  19.882  1.00  0.00           O  
ATOM     11  O   UNL A   1      29.971  13.422  23.309  1.00  0.00           O  
ATOM     12  C   UNL A   1      26.485  11.933  20.313  1.00  0.00           C  
ATOM     13  C   UNL A   1      26.239  11.767  18.940  1.00  0.00           C  
ATOM     14  C   UNL A   1      25.188  10.956  18.505  1.00  0.00           C  
ATOM     15  C   UNL A   1      24.391  10.318  19.444  1.00  0.00           C  
ATOM     16  C   UNL A   1      24.638  10.462  20.807  1.00  0.00           C  
ATOM     17  C   UNL A   1      25.685  11.264  21.252  1.00  0.00           C  
ATOM     18  O   UNL A   1      23.816   9.795  21.673  1.00  0.00           O  
ATOM     19  O   UNL A   1      23.350   9.546  19.017  1.00  0.00           O  
ATOM     20  O   UNL A   1      27.996  11.567  22.786  1.00  0.00           O  
ATOM     21  O   UNL A   1      29.990  17.904  18.716  1.00  0.00           O  
ATOM     22  O   UNL A   1      31.186  15.780  22.768  1.00  0.00           O  
ATOM     23  H   UNL A   1      23.120   9.263  21.342  1.00  0.00           H  
ATOM     24  H   UNL A   1      23.184   9.449  18.100  1.00  0.00           H  
ATOM     25  H   UNL A   1      27.333  10.936  22.586  1.00  0.00           H  
ATOM     26  H   UNL A   1      29.492  17.955  17.924  1.00  0.00           H  
ATOM     27  H   UNL A   1      31.794  16.476  22.922  1.00  0.00           H  
CONECT    1    6    6    2                                            
CONECT    2    1    3    3   22                                       
CONECT    3    4    2    2    7                                       
CONECT    4    5    5   10    3                                       
CONECT    5    6    4    4                                            
CONECT    6   21    5    1    1                                       
CONECT    7    3    8   11   11                                       
CONECT    8    9    9    7   20                                       
CONECT    9   10   12    8    8                                       
CONECT   10    4    9                                                 
CONECT   11    7    7                                                 
CONECT   12   13   13    9   17                                       
CONECT   13   14   12   12                                            
CONECT   14   13   15   15                                            
CONECT   15   14   14   19   16                                       
CONECT   16   15   17   17   18                                       
CONECT   17   12   16   16                                            
CONECT   18   16   23                                                 
CONECT   19   15   24                                                 
CONECT   20    8   25                                                 
CONECT   21    6   26                                                 
CONECT   22    2   27                                                 
CONECT   23   18                                                      
CONECT   24   19                                                      
CONECT   25   20                                                      
CONECT   26   21                                                      
CONECT   27   22                                                      
MASTER        0    0    0    0    0    0    0    0   27    0   27    0
END

Is it possible to make the MMPBSA.py routine ignore these lines and complete the calculations?
Otherwise, we will have to open and delete each of these lines in each ligand file.

Thanks,
Evenilton

**Comment by sahakyanhk** [comment]
Yes, records about connections often cause errors in the antechamber. Now it should ignore all lines in PDB except ATOM and HETATM.

**Comment by EveniltonPCosta** [comment]
Hi Harut,
Excellent, with this edit, lines containing the term 'CONECT' are ignored and the calculation proceeds without errors.

I realized that I can't run the calculation with 20 ligands at the same time, when I try to do that, some error occurs and 3-4 ligands are not calculated.

But by dividing ligands in 2 folders with 10, all ligands from each folder are calculated without errors.

If you allow me, I would like to post a tutorial here, in a new issue with a new title, to help users who have difficulty with programming and using the terminal.

In this tutorial, I will try to explain how to install ambertools 22 via Conda, export important files and folders in the bashrc.

Maybe, with these tips, more users will use this great tool that you developed.

**Comment by sahakyanhk** [comment]
Hi Evenilton, 

Thanks for your interest. Of course, you can modify the script and make tutorials, iPBSA is entirely open.  

That is strange that you get errors when you run 20 ligands simultaneously. Please open a new issue with examples. I will try to fix this problem.

**Comment by EveniltonPCosta** [comment]
Thanks!
I'll close this and I'll send you the PDBs.
